Подключение библиотеки pandas

In [10]:
import pandas as pd

Первая и самая важная команда для начала работы по анализу данных всемирно считается read_csv, для ее применения нужно знать место расположения файла на локальном устройстве, а так же добавить дополнительные "слеши", поскольку pandas треует их двойном размере. сохраним загруженный документ в созданый обект типа "pandas.core.frame.DataFrame"

In [11]:
df = pd.read_csv('C:\\Users\\Pila\\Downloads\\6games.csv')

просмотр первых 20-ти строк

In [13]:
df.head(20)

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,23.20,2.26,4.22,0.58,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,11.28,9.14,6.50,2.88,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,14.44,6.94,4.70,2.24,87.0,8.4,E
9,Duck Hunt,NES,1984.0,Shooter,26.93,0.63,0.28,0.47,NaN,NaN,NaN
10,Nintendogs,DS,2005.0,Simulation,9.05,10.95,1.93,2.74,NaN,NaN,NaN
11,Mario Kart DS,DS,2005.0,Racing,9.71,7.47,4.13,1.90,91.0,8.6,E
12,Pokemon Gold/Pokemon Silver,GB,1999.0,Role-Playing,9.00,6.18,7.20,0.71,NaN,NaN,NaN
13,Wii Fit,Wii,2007.0,Sports,8.92,8.03,3.60,2.15,80.0,7.7,E
14,Kinect Adventures!,X360,2010.0,Misc,15.00,4.89,0.24,1.69,61.0,6.3,E
15,Wii Fit Plus,Wii,2009.0,Sports,9.01,8.49,2.53,1.77,80.0,7.4,E
16,Grand Theft Auto V,PS3,2013.0,Action,7.02,9.09,0.98,3.96,97.0,8.2,M
17,Grand Theft Auto: San Andreas,PS2,2004.0,Action,9.43,0.40,0.41,10.57,95.0,9,M
18,Super Mario World,SNES,1990.0,Platform,12.78,3.75,3.54,0.55,NaN,NaN,NaN
19,Brain Age: Train Your Brain in Minutes a Day,DS,2005.0,Misc,4.74,9.20,4.16,2.04,77.0,7.9,E

Для дальнейший работы, нужно оценить типы данных каждого столбца и узнать дополнительную информацию о их состоянии, к примеру количество ненулевых объектов, общий вес файла и радиус индексов

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16713 non-null  object
 1   Platform         16715 non-null  object
 2   Year_of_Release  16446 non-null  float64
 3   Genre            16713 non-null  object
 4   NA_sales         16715 non-null  float64
 5   EU_sales         16715 non-null  float64
 6   JP_sales         16715 non-null  float64
 7   Other_sales      16715 non-null  float64
 8   Critic_Score     8137 non-null   float64
 9   User_Score       10014 non-null  object
 10  Rating           9949 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.4+ MB

В предыдущем шаге, были выявлены проблемы с названиями, было принято решение испавить их используя команду rename

In [21]:
df = df.rename(columns={"Name": "name","Platform":"platform","Year_of_Release":"year_of_release",
                        "Genre":"genre","NA_sales":"na_sales","EU_sales":"eu_sales",
               "JP_sales":"jp_sales","Other_sales":"other_sales","Critic_Score":"critic_score",
               "User_Score":"user_score","Rating":"rating"})

In [22]:
df

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16710,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.00,0.01,0.00,NaN,NaN,NaN
16711,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.00,0.00,NaN,NaN,NaN
16712,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.00,0.01,0.00,NaN,NaN,NaN
16713,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,NaN,NaN,NaN
16714,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.00,0.01,0.00,NaN,NaN,NaN

Поскольку в работе были обнаружены пропуски, требуется применить команду fillna(0),чтобы не лишиться строк с важными данными, заполним значения NaN

In [23]:
df['name'] = df['name'].fillna(0)
df['platform'] = df['platform'].fillna(0)
df['year_of_release'] = df['year_of_release'].fillna(0)
df['genre'] = df['genre'].fillna(0)
df['na_sales'] = df['na_sales'].fillna(0)
df['eu_sales'] = df['eu_sales'].fillna(0)
df['jp_sales'] = df['jp_sales'].fillna(0)
df['other_sales'] = df['other_sales'].fillna(0)
df['critic_score'] = df['critic_score'].fillna(0)
df['user_score'] = df['user_score'].fillna(0)
df['rating'] = df['rating'].fillna(0)

проверка данных на наличие дубликатов, если они есть – произойдет удаление

In [25]:
df = df.drop_duplicates()
df = df.drop_duplicates().reset_index()
df

,index,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,0.0,0,0
2,2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
16710,16710,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.00,0.01,0.00,0.0,0,0
16711,16711,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.00,0.00,0.0,0,0
16712,16712,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.00,0.01,0.00,0.0,0,0
16713,16713,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,0.0,0,0
16714,16714,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.00,0.01,0.00,0.0,0,0

In [48]:
def convert_currency(val):
    """
    Преобразует числовое значение строки в число с плавающей точкой:
     - удаляет $
     - удаляет запятые
     - преобразует в число с плавающей точкой
    """
    new_val = val.replace(',', '')
    return float(new_val)

In [53]:
#df['user_score'].apply(convert_currency)

#df['user_score'] = df['user_score'].astype('float')

#df["user_score"] = [float(str(i).replace(",", "")) for i in df["user_score"]]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            16715 non-null  int64
 1   name             16715 non-null  object
 2   platform         16715 non-null  object
 3   year_of_release  16715 non-null  float64
 4   genre            16715 non-null  object
 5   na_sales         16715 non-null  float64
 6   eu_sales         16715 non-null  float64
 7   jp_sales         16715 non-null  float64
 8   other_sales      16715 non-null  float64
 9   critic_score     16715 non-null  float64
 10  user_score       16715 non-null  object
 11  rating           16715 non-null  object
dtypes: float64(6), int64(1), object(5)
memory usage: 1.5+ MB

Сводная таблица игр, по названию и дате релиза

In [62]:
data_pivot = pd.pivot_table(df,index=['name'],values = ['year_of_release'])
sorted_df = data_pivot.sort_values(by='year_of_release')
sorted_df

                                                    year_of_release
name
Tube Slider                                                     0.0
Super Robot Wars OG Saga: Masou Kishin II - Rev...              0.0
Half-Minute Hero 2                                              0.0
The King of Fighters: Maximum Impact - Maniax                   0.0
Tribes: Aerial Assault                                          0.0
...                                                             ...
Prison Architect                                             2016.0
PriPara Mezameyo! Megami no Dress Design                     2016.0
Pokken Tournament                                            2016.0
Reco Love: Blue Ocean                                        2016.0
Mega Man Legacy Collection                                   2016.0

[11560 rows x 1 columns]

In [65]:
data_pivot = pd.pivot_table(df,index=['name'],values = ['other_sales'])
sorted_df = data_pivot.sort_values(by='other_sales',ascending=False)
sorted_df

                                 other_sales
name
Wii Sports                              8.45
Gran Turismo 4                          7.53
Mario Kart Wii                          3.29
Wii Sports Resort                       2.95
New Super Mario Bros.                   2.88
...                                      ...
Legoland                                0.00
Legends of Oz: Dorothy's Return         0.00
Legend: Hand of God                     0.00
Legend of the Dragon                    0.00
¡Shin Chan Flipa en colores!            0.00

[11560 rows x 1 columns]